### ISSUE TITLE
Fix: Constant features with bivariate feature functions

### ISSUE THREAD

**Issue by jbschiratti** [mne-tools/mne-features#11]
```
import numpy as np
from mne_features.feature_extraction import extract_features

rng = np.random.RandomState(42)
sfreq = 256.
X = rng.standard_normal((2, 1, int(sfreq)))
# data with only 2 epochs and 3 channels
data = np.concatenate([X, X ** 2, X ** 3], axis=1)

sel_funcs = ['spect_corr']
Xnew = extract_features(data, sfreq, sel_funcs, {'spect_corr__db': False})
print(Xnew)
```
outputs:
```
[[ 1.00000000e+00 -2.89225913e-01 -2.92641378e-01  1.00000000e+00
  -8.30714688e-01  1.00000000e+00  0.00000000e+00  1.16927731e+00
   1.83072269e+00]
 [ 1.00000000e+00 -4.14820591e-01 -2.88700088e-02  1.00000000e+00
  -8.97548079e-01  1.00000000e+00  4.44089210e-16  1.02198101e+00
   1.97801899e+00]]
```
This example shows that, with `spect_corr`as feature function, some features (column index 0, 3, 5) are constant. These constant features were computed from pairs of channels of the form `(data[i, :], data[i, :])`. Same is true with other bivariate feature functions.

In some cases (using `Xnew` for classification, for instance), one may wish to remove these constant features. This could be done by post-processing the extracted features with `sklearn.feature_selection.VarianceThreshold`. However, having an optional parameter (like `include_diag=False`) in bivariate features might be a good idea to remove features corresponding to pairs of channels of the form `(data[i, :], data[i, :])`.

**Comment by agramfort** [comment]
yes don't include it by default.
