### ISSUE TITLE
ENH: Implement a function to fine-tune features extraction functions' parameters.

### ISSUE THREAD

**Issue by GuillaumeCorda** [mne-tools/mne-features#16]
It would be really useful to have a function that works in the same way as sklearn's GridSearchCV does allowing to fine-tune parameters from the univariate.py and bivariate.py functions. In order to do so a classification problem to solve is needed which could be seizure detection.

**Comment by jbschiratti** [comment]
+1

**Comment by jbschiratti** [comment]
See #17.
