### ISSUE TITLE
ENH: Enable caching fitted transformers

### ISSUE THREAD

**Issue by jbschiratti** [mne-tools/mne-features#18]
As @agramfort suggested in #17, it would be a good idea to have a `memory` parameter (like in <a href="http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html">sklearn.pipeline.Pipeline</a>) in `extract_features` and `FeatureExtractor` to allow caching the fitted transformers.

**Comment by agramfort** [comment]
idea is:

memory=None

in constructor

then inside
mem = Memory(self.memory)

X = mem.cache(extract_features)(...)
