### ISSUE TITLE
ENH: Use custom feature functions

### ISSUE THREAD

**Issue by jbschiratti** [mne-tools/mne-features#20]
Although MNE-features proposes a large number of feature functions, a user might want to use MNE-features with his own feature functions. The function `extract_features` or the class `FeatureExtractor` should allow the user to work with his own feature functions.

**Comment by jbschiratti** [comment]
As it is now, in `extract_features`, we do:

    list_of_transformers = [(n, FeatureFunctionTransformer(func=feature_funcs[n])) for n in selected_funcs]

If a user was to pass a list of tuples (called `additional_features`), each tuple being of the form `(str, callable)`, we could easily do:

    _intrinsic_features = [(n, feature_funcs[n]) for n in selected_funcs]
    _extrinsic_features = list(additional_features)
    _features = _intrinsic_features + _extrinsic_features
    list_of_transformers = [(n, FeatureFunctionTransformer(func=func)) for n, func in _features]

This would do the job.

**Comment by agramfort** [comment]
Why a new parameter? You should detect if a string or not is passed

**Comment by jbschiratti** [comment]
Ok. I'm not sure I see what you mean. 
Instead of having only strings in `selected_funcs`, one could have strings and/or callable ?

**Comment by agramfort** [comment]
>
> Something like: selected_funcs = ['mean', 'var', ('myfun1', fun1),
> ('myfun2', fun2)].
>

yes perfect
