### ISSUE TITLE
FIX: Generalizable definition of aliases

### ISSUE THREAD

**Issue by jbschiratti** [mne-tools/mne-features#21]
In `extract_features` or `FeatureExtractor`, the parameter `selected_funcs` is a list of aliases (str) which correspond to feature functions. For simplicity (and generalizability), the aliases should correspond to the name of the feature function, without `compute_`. 

- Each feature functions should have a name of this form: `compute_[suffix]`
- For each feature function, the corresponding alias should simply be: `[suffix]`.

**Comment by jbschiratti** [comment]
@GuillaumeCorda If you want to make a PR for this, go for it !

**Comment by GuillaumeCorda** [comment]
@jbschiratti Going to work on this today, thanks !
