### ISSUE TITLE
ENH: Meaningful tests

### ISSUE THREAD

**Issue by jbschiratti** [mne-tools/mne-features#30]
As @agramfort noted, the tests (for univariate and bivariate) feature functions only check that the returned arrays have the right shape. It is enough to check that a function does not fail on random input data but such tests do not ensure that the features are correctly implemented... 

Tests need to be improved.

**Comment by jbschiratti** [comment]
While writing some tests, I realized that the behavior of `compute_zero_crossings` is dubious:

`compute_zero_crossings(np.array([[1., 1., 0., -1., -1.]]))` returns `2` (expected `1`)
`compute_zero_crossings(np.array([[0., 0., 1., -1., -1.]]))` returns `2` (expected `3`)
`compute_zero_crossings(np.array([[0., 0., 1., -1., 0.]]))` returns `3` (expected `4`).

**Comment by agramfort** [comment]
You mean  buggy :)

**Comment by jbschiratti** [comment]
I started a PR for this issue in #31.

@GuillaumeCorda If you want to improve some tests, go for it! Make a PR on my branch (`tests_refactoring`) if you want to add something.
