### ISSUE TITLE
compute_pow_freq_bands returns ratios

### ISSUE THREAD

**Issue by agramfort** [mne-tools/mne-features#32]
it would be nice to be able to return the ratios between powers in bands.

cc @l-omar-chehab

**Comment by l-omar-chehab** [comment]
Agreed. It shouldn't be hard to write, using the pow band function already existing in mne features. 

Not optimized as yet, but maybe something like this?

# from the output of the existing pow band mne function
# we have a  pow_band data frame where column names = [‘delta', 'theta', 'alpha', 'beta', 'gamma']
freqs = list(pow_band.columns)  
 
# non redundant ratio pairs 
pairs = []
for idx in range(len(pow_bands) - 1):
    freq1 = freqs[idx]
    pair1 = pow_band_names[idx]
    for freq2 in freqs[idx + 1:]:
        pairs.append((freq1, freq2))

# computing their values
for pair in pairs:
   pow_band[pair[0] + '_' + pair[1] + '_ratio'] = pow_band[pair[0]] / time_features[pair[1]]

# removing the initial pow bands, leaving only the ratios
pow_band = pow_band.drop(columns=freqs)

**Comment by l-omar-chehab** [comment]
As soon as I get back, I will post a snippet of code for fit / fit error functionality for the log log of the 1/f prototypical freq-power curve

**Comment by l-omar-chehab** [comment]
def deviation_inverse_freq_curve(source):

    source = source[np.newaxis, :]

    out = power_spectrum(sfreq=sfreq, data=source)
    power = out[0][0]
    freq = out[1]

    condition = (freq <= 50) & (freq >= 0.1)
    freq = freq[condition]
    power = power[condition]

    freq = 20 * np.log10(freq)
    power = 20 * np.log10(power)

    lm = LinearRegression()
    lm.fit(freq[:, np.newaxis], power[:, np.newaxis])

    slope = lm.coef_[0][0]
    intercept = lm.intercept_
    predictions = lm.predict(freq[:, np.newaxis]).flatten()
    mse = metrics.mean_squared_error(power, predictions)
    R2 = metrics.explained_variance_score(power, predictions)

    result = np.array([slope, intercept, mse, R2])
    result = result[:, np.newaxis]

    return(result)

**Comment by jbschiratti** [comment]
About the ratios between power in bands, I agree ! It's a must-have for MNE-features.

What about adding an optional parameter `ratios` to `compute_pow_freq_bands` to define the pairs of [frequency] bands used to compute the ratios? `ratios` could be a `(n_ratios, 2)` array such that: `ratios[i, 0]` (resp. `ratios[i, 1]`) is the index of the band used to compute the numerator (resp. denorminator) of the ratio. For instance, to compute the ratios {theta/delta, alpha/theta, beta/alpha}, we would have: `ratios = np.array([[1, 0], [2, 1], [3, 2]])`.

In `compute_pow_freq_bands` we could have something like:

    if ratios is not None:
        n_ratios = ratios.shape[0]
        band_ratios = np.empty((n_channels, n_ratios))
        for j in range(n_ratios):
            band_ratios[:, j] = np.divide(pow_freq_bands[:, ratios[j, 0]], pow_freq_bands[:, ratios[j, 1]])
    return np.r_[pow_freq_bands.ravel(), band_ratios.ravel()]

It would also be possible to return only `band_ratios.ravel()`.
With this approach, the frequency bands can be whatever the user wants. The frequency bands do not necessarily have to be: 'delta', 'theta', 'alpha', 'beta', 'gamma'.

**Comment by l-omar-chehab** [comment]
Sounds good!
(to be fair the 'alpha', 'beta' etc. were generic, it would've been pow band output columns, whichever they were) 

The ratios parameter looks neat! 

Suggestion: as you said, ratios could take the values None or an array of specified pairs, how about adding a case where it could take the string 'all' and where the function would return all non-redundant pairs (user-friendly if defining many freq bands). 

Question: if the ratios parameter is activated, should the pow_band function also return the power bands on top, giving the user the opportunity to manually remove them if needed? Or should a parameter control a case where the function returns pow band ratios without the pow bands?

**Comment by jbschiratti** [comment]
> it would've been pow band output columns, whichever they were

I agree ! However, IMO, naming the frequency bands ('delta', 'theta', 'alpha', ...) could make things complicated. If `freq_bands = np.array([0.1, 4, 8, 12, 30, 40, 50, 60, 70, 85, 100, 140, 180])`, which names would we use ? (There are 12 frequency bands...) Also, if `freq_bands = np.array([2, 40])`, these names could be misleading as it overlaps the usual delta, theta, alpha and theta bands.

Good idea, we should also allow `ratios='all'` . 

To return only the ratios of power in bands, we could have an optional parameter `return_ratios_only=True`. Another solution would be to have another feature function `compute_pow_ratios` which wraps `compute_pow_freq_bands`.

@agramfort What do you think about this?

**Comment by agramfort** [comment]
I would add a parameter called ratios that can take 3 values : None (no ratios), 'all' (return psds and all the ratios), 'only' (return only the ratios).

I don't think it's a real use case to return a subset of the ratios at this stage.

@l-omar-chehab please open another issue for deviation_inverse_freq_curve. It's a different pb.

**Comment by jbschiratti** [comment]
I opened #33 to add a `ratios` parameter to `compute_pow_freq_bands`.
