### ISSUE TITLE
Use a threshold to compute zero-crossings

### ISSUE THREAD

**Issue by jbschiratti** [mne-tools/mne-features#45]
Example:
```
import numpy as np
from mne_features.univariate import compute_zero_crossings

sig = np.sin(np.linspace(0, 4 * 2 * np.pi, 10))
z = compute_zero_crossings(sig[None, :])
```
In this example, `y` is given by:
```
array([ 0.00000000e+00,  3.42020143e-01, -6.42787610e-01,  8.66025404e-01,
       -9.84807753e-01,  9.84807753e-01, -8.66025404e-01,  6.42787610e-01,
       -3.42020143e-01, -9.79717439e-16])
```
And the result `z` of `compute_zero_crossings` is ``array([8.])``.

-----
Depending on whether the last value of `y` should be treated as 0, `compute_zero_crossings` might give wrong results. To address this problem, `compute_zero_crossings` should use a threshold to determine whether a value is treated as 0. For instance:

```
compute_zero_crossings(sig[None, :], threshold=1e-12)  # returns array([9.])
compute_zero_crossings(sig[None, :], threshold=np.finfo(np.float64).eps)  # returns array([8.])
```

**Comment by agramfort** [comment]
had the threshold param and set it to np.finfo(np.float64).eps by default

**Comment by jbschiratti** [comment]
See #46.
