### ISSUE TITLE
Error installing mne-features

### ISSUE THREAD

**Issue by akatav** [mne-tools/mne-features#47]
Hi,
I have all required packages listed as requirements with right versions, but still i get the following:
ERROR: Could not find a version that satisfies the requirement mne-features (from versions: none)
ERROR: No matching distribution found for mne-features
On trying:
pip3 install git+https://github.com/mne-tools/mne-features.git#egg=mne_features --no-cache-dir
i get the following:
  ERROR: Complete output from command /home/venkat/miniconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-wpgqjkz0/python-mne-features/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/home/venkat/miniconda3/lib/python3.6/tokenize.py", line 452, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-wpgqjkz0/python-mne-features/setup.py'

  ERROR: Failed cleaning build dir for python-mne-features
Successfully built python-mne-features
Failed to build python-mne-features

How to resolve this?

**Comment by agramfort** [comment]
mne-features list a number of dependencies:

https://github.com/mne-tools/mne-features/blob/master/setup.py#L61

I don't know which one poses a problem. If any.

@akatav you can download the repo https://github.com/mne-tools/mne-features/archive/master.zip
then extract content and do:

cd mne-features-master
pip install -e .

**Comment by guiweber** [comment]
I'm also getting this error when I try to install with pip

`pip install mne-features`

`Collecting mne-features
  ERROR: Could not find a version that satisfies the requirement mne-features (from versions: none)
ERROR: No matching distribution found for mne-features`

I have all the dependencies installed. If this is not the proper way to install the module, it would be nice to clarify the instructions in the readme.

**Comment by agramfort** [comment]
mne-features has never been pushed to pypi so you have to rely on :

pip install git+https://github.com/mne-tools/mne-features.git#egg=mne_features
