### ISSUE TITLE
transform() takes 2 positional arguments but was given 3

### ISSUE THREAD

**Issue by akatav** [mne-tools/mne-features#48]
Trying to run the example - https://github.com/mne-tools/mne-features/blob/master/examples/plot_seizure_example.py throws error as below: 

~/miniconda3/lib/python3.6/site-packages/mne_features/feature_extraction.py in transform(self, X, y)
     67             details.
     68         """
---> 69         X_out = super(FeatureFunctionTransformer, self).transform(X, y)
     70         self.output_shape_ = X_out.shape[0]
     71         return X_out

TypeError: transform() takes 2 positional arguments but 3 were given

Is this a scikit-learn version issue? sklearn is up to date.

**Comment by jbschiratti** [comment]
I ran this example locally and was not able to reproduce this error. 
Could you, please, provide us with a minimal working example which allows to reproduce it?

**Comment by jbschiratti** [comment]
See #49.
