### ISSUE TITLE
Why mne-feature take long time to load?

### ISSUE THREAD

**Issue by balandongiv** [mne-tools/mne-features#66]
Relative to mne-python, mne-feature take significantly long time to load during import calling.

May I know whether there is workaround to improve this

```
import timeit
start = timeit.timeit()

import mne
end = timeit.timeit()

start1 = timeit.timeit()

from mne_features.feature_extraction import extract_features
end1 = timeit.timeit()

print(f'{end - start} vs {end1 - start1}')
```

Produce
```

0.0004304109897930175 vs 1.1699972674250603e-05


0.0012418319820426404 vs 0.00043890299275517464


```

**Comment by agramfort** [comment]
you could try https://pypi.org/project/import-profiler/ to profile

I've used this package successfully in the past

>

**Comment by balandongiv** [comment]
Thanks for response @agramfort .

While Im able to profile the `import mne`, profile both the `import mne_features` and  `from mne_features.feature_extraction import extract_features` return the following error

`ValueError: level must be >= 0`


The code

```

from import_profiler import profile_import

with profile_import() as context:

    import mne_features

    context.print_info()
```

Im able to use this package successfully, the only issue is the  low load time.

**Comment by agramfort** [comment]
note that mne-features uses numba so it has some compilation time but it
should not happen during loading

you can find the fix to the error above due to Python 3 on the web

>

**Comment by balandongiv** [comment]
Hi @agramfort , Im using Python build in profiler [tuna](https://github.com/nschloe/tuna).

For comparison, I run both `mne-python` and `mne-feature`

![profile for mne-python](https://user-images.githubusercontent.com/22090092/128866194-86e797c2-9c81-4abd-96d8-7fcfb1d1d5ea.png)

profile for mne-python



![profile for import mne_features](https://user-images.githubusercontent.com/22090092/128866304-b406cd46-ac7b-4cbd-97b6-6788a0812505.png)


line under the file  `timit_package.py`
```
# Decoment either 1
import mne
# from mne_features.feature_extraction import extract_features
```

In terminal
`python -mcProfile -o program.prof timit_package.py`

link to the tune html report: https://drive.google.com/file/d/1Xw4BO25VA1u40IvNDMzg6WBgfX2yctKI/view?usp=sharing

**Comment by agramfort** [comment]
I don't have time to investigate sorry. Feel free to submit a pull request
if you see a way to improve the situatiion

>

**Comment by jbschiratti** [comment]
Hi, I'll investigate in a week, when I'm back from vacation (if the issue is still open).

**Comment by balandongiv** [comment]
For development purpose, I prefer to disable the `jit` via
```

from numba import jit, config
config.DISABLE_JIT = True

```
and set 

`config.DISABLE_JIT = False`

for production stage
