### ISSUE TITLE
Inconsistency for compute_time_corr

### ISSUE THREAD

**Issue by eduvalero** [mne-tools/mne-features#67]
I noticed the [documentation](https://mne.tools/mne-features/generated/mne_features.bivariate.compute_time_corr.html#mne_features.bivariate.compute_time_corr) of the time_corr function states that the default values of the parameters are:
- with_eigenvalues: False
- include_diag: True

However, in the [source code](https://github.com/mne-tools/mne-features/blob/master/mne_features/bivariate.py) these values are changed (see compute_time_corr):
- with_eigenvalues: True
- include_diag: False

This creates an unexpected behaviour when calling time_corr. I don't know if the fix must be applied to the docs or the code.

**Comment by agramfort** [comment]
good catch. can you send us a PR?

>

**Comment by jbschiratti** [comment]
Thanks @eduvalero for spotting this! Feel free to submit a PR

**Comment by eduvalero** [comment]
Done.

**Comment by jbschiratti** [comment]
Fixed by #68.
