### ISSUE TITLE
extract_features returns TypeError

### ISSUE THREAD

**Issue by kwdoyle** [mne-tools/mne-features#69]
mne_features.feature_extraction.extract_features() now returns the error TypeError: _check_input() missing 1 required keyword-only argument: 'reset'. 

Checking the arguments of this method on line 87 within feature_extraction.py does show that 'reset' is apparently an existing argument, as `self._check_input.__code__.co_varnames` returns ('self', 'X', 'reset')

**Comment by jbschiratti** [comment]
This should be fixed by #71.
