### ISSUE TITLE
Integrate funcs_params to the FeatureExtractor

### ISSUE THREAD

**Issue by balandongiv** [mne-tools/mne-features#74]
Currently, the `FeatureExtractor` does not have the capability to accept `funcs_params` as posses by `extract_features`. 

This making it difficult to supply 'pow_freq_bands'  if the data having sampling rate of, say 100 Hz. Which will produce

> ValueError: The entries of the given `freq_bands` parameter ([  0.5   4.    8.   13.   30.  100. ]) must be positive and less than the Nyquist frequency.

Maybe the dev team can consider this issue.

**Comment by jbschiratti** [comment]
The FeatureExtractor accepts a `params` argument which is the same as `func_params` for `extract_features`.
