### ISSUE TITLE
Normalization with log power in compute_pow_freq_bands

### ISSUE THREAD

**Issue by thomasfillon** [mne-tools/mne-features#79]
Hi ,

Just looking at the code, there might be an issue with the normalization with the combination `log=True`, `normalize=True`  in the function `compute_pow_freq_bands()` at https://github.com/mne-tools/mne-features/blob/399092ab015995afc66453ecc99fbe3e502f9a9a/mne_features/univariate.py#L722

```
    pow_freq_bands = np.empty((n_channels, n_freq_bands))
    for j in range(n_freq_bands):
        mask = np.logical_and(freqs >= fb[j, 0], freqs <= fb[j, 1])
        psd_band = psd[:, mask]
        pow_freq_bands[:, j] = np.sum(psd_band, axis=-1)

    if log:
        pow_freq_bands = np.log10(pow_freq_bands)

    if normalize:
        pow_freq_bands = np.divide(pow_freq_bands,
                                   np.sum(psd, axis=-1)[:, None])
```

If I'm not wrong the normalization should be done before apply the log:

```
  if normalize:
        pow_freq_bands = np.divide(pow_freq_bands,
                                   np.sum(psd, axis=-1)[:, None])

   if log:
        pow_freq_bands = np.log10(pow_freq_bands)

  
```

**Comment by jbschiratti** [comment]
Thanks @thomasfillon for opening this issue, makes sense! Can you start a PR to fix this? 🙏

**Comment by agramfort** [comment]
I agree it makes more sense to divide by total power and then do a log
transform

**Comment by thomasfillon** [comment]
Are there any reason to return `log10(power)` instead of `10 log10(power)`  ?
```
   if log:
        pow_freq_bands = np.log10(pow_freq_bands)
```

**Comment by agramfort** [comment]
10 log10 could be called dB but it has no effect on downstream predicitons

**Comment by thomasfillon** [comment]
> 10 log10 could be called dB but it has no effect on downstream predicitons

@agramfort yes I know , but given that the function is supposed to return power values,  I feel unconfortable not returning `dB` ;-)
Even if it has no effect on downstream predicitons it could be useful for other use case (like computing the power in dB scale ) .

With this PR, could I also change the return value to dB or should I keep it like it is and stick with Bel ?

**Comment by agramfort** [comment]
No objection to return proper dB
