### ISSUE TITLE
Package is not installable using setuptools

### ISSUE THREAD

**Issue by wvxvw** [mne-tools/mne-features#83]
The package is broken in many ways:

1. It has a compile-time dependency on NumPy, but doesn't declare it.
2. It has a source distribution for version 0.2, but no distributable packages for this version, and because of that `pip` or `setuptools` will idiotically try to build the package while installing it, but will fail because of (1).
3. Finally, if you even manage to fix the NumPy dependency, the package also depends on `mne` package, but is required to install `mne`... which creates a dependency loop. This somehow works for `pip` as it is either able to break dependency loops, or ignores the error (more likely), but fails with `setuptools`. Thus any package that tries to depend on `mne-features` becomes also impossible to install.

**Comment by wvxvw** [comment]
Hi guys. I saw that you addressed the issue, but can you please publish the Wheel, or at least the updated tarball to PyPI? Thanks.

**Comment by agramfort** [comment]
0.2.1 is online https://pypi.org/project/mne-features/0.2.1/
