### ISSUE TITLE
ModuleNotFoundError: No module name 'utils'

### ISSUE THREAD

**Issue by nsp2012** [mne-tools/mne-features#86]
Hi,

I am trying to calculate the spectral edge frequency of my EEG Data using men-features. I am currently using Jupyter notebook via Anaconda-Navigator and I have installed mne environment, but I keep getting this "ModuleNotFoundError: No module name 'utils'" error... I don't have much experience with coding and python, so I will be greatly appreciated it if you could explain thoroughly how to import the features below. 

from utils import (power_spectrum, _embed, _filt, _get_feature_funcs,
                    _get_feature_func_names, _wavelet_coefs, _idxiter,
                    _psd_params_checker)

Thanks in advance.

**Comment by jbschiratti** [comment]
Hello,

Instead of doing `from utils import power_spectrum`, you should do: `from mne_features.utils import power_spectrum`.

**Comment by jbschiratti** [comment]
Closing this issue as the suggestion should fix the problem.
