### ISSUE TITLE
 data : ndarray, shape (n_channels, n_times)

### ISSUE THREAD

**Issue by nsp2012** [mne-tools/mne-features#87]
Hi,

I have a set of EEG data that contains EEG signal of 4 channel, like so.

[[  3.9401  -5.4757   8.6351 -13.8168]
 [  4.5597  -9.3532  13.0823 -18.3166]
 [  6.3138 -10.7552  16.6764 -18.6332]
 ...
 [-24.2438  11.6975 -56.4585  47.0863]
 [-24.9816  11.1459 -54.4973  47.6616]
 [-23.3121  14.4831 -49.4173  49.9967]]

What do I need to do to my data set so that I can put that into "compute_spect_edge_freq" code? 

I would appreciate it if someone could explain "data : ndarray, shape (n_channels, n_times)".

Thanks in advance.

**Comment by jbschiratti** [comment]
Have a look at [the examples](https://mne.tools/mne-features/auto_examples/index.html), it will give you an idea about how `mne_features` work. Also, have a look at this unit [test](https://github.com/mne-tools/mne-features/blob/2fa2b2c974f4a6b708a2f073e1b43b6c9591a2d5/mne_features/tests/test_univariate.py#L599) with toy data.

**Comment by jbschiratti** [comment]
Below, `arr` is a `(2,4)` Numpy array. 

If you were to pass this  to `compute_spect_edge_freq`, it would be understood as: 2 channels, 4 time points per channel.

```
import numpy as np

arr = np.array([[ 3.9401, -5.4757, 8.6351, -13.8168], [ 4.5597, -9.3532, 13.0823, -18.3166]])
```

**Comment by jbschiratti** [comment]
Closing as this is not an issue (or a feature request).
